### ISSUE TITLE
Ref Paths don't get adjusted to account for different directories

### ISSUE THREAD

**Issue by ptasev** [robertmassaioli/openapi-merge#103]
Reference paths do not get updated when merging. Imagine that `Proj2/OpenAPI.json` references a component from `SomeRef.json`. When this file gets merged into `OpenAPIOut.json`, the $ref path still relative to `Proj2` dir, rather than `Proj1` (output dir).

Folder structure:
Root
- Proj1
  - OpenAPI.json
  - openapi-merge.json
- Proj2
  - OpenAPI.json
  - SomeRef.json

`Proj2/OpenAPI.json`
```json
"parameters": [
  {
    "$ref": "SomeRef.json#/components/parameters/myParam"
  }
]
```
In `OpenAPIOut.json` should be, but is same as above:
```json
"parameters": [
  {
    "$ref": "../Proj2/SomeRef.json#/components/parameters/myParam"
  }
]
```

Input:
`openapi-merge.json`
```json
{
  "inputs": [
    {
      "inputFile": "OpenAPI.json"
    },
    {
      "inputFile": "../Proj2/OpenAPI.json"
    }
  ],
  "output": "OpenAPIOut.json"
}
```

**Comment by resurtm** [comment]
https://github.com/robertmassaioli/openapi-merge/issues/48#issuecomment-1074485136
