### ISSUE TITLE
Need code examples

### ISSUE THREAD

**Issue by incker** [robertmassaioli/openapi-merge#31]
I am sorry for asking, if I want generate 2 swagger specs that are a bit differ from each other in some routes, does `openapi-merge` will help me?

Is there any minimal exapmle code how to run merging like "hello world" + "hello world 2" to clone from git and run?

**Comment by robertmassaioli** [comment]
Hi @incker , unfortunately that's not enough information for me to help you. Why don't you try and use openapi-merge and if you have issues then raise that as a request?

**Comment by robertmassaioli** [comment]
You want an example of how to use the library. I can probably do that.

**Comment by chris5marsh** [comment]
I'd like this too - I've used the CLI package successfully and I'm now looking to move the merge into a script.

I'm having a dig around the code to see if I can figure out how to use it, but if you have some code samples handy it would be great to have them.

**Comment by chris5marsh** [comment]
I have it working - here's a simplified version of what I'm doing:
```js
const fs = require('fs');
const yaml = require('js-yaml');
const merge = require('openapi-merge').merge;

const loadOas = async (filePath) => {
  return new Promise((resolve, reject) => {
    fs.readFile(filePath, (err, result) => {
      if (err) {
        reject(err);
      } else {
        const yamlContents = yaml.load(result);
        resolve(yamlContents);
      }
    });
  });
};

const filesToMerge = [
  'path/to/oas1.yml',
  'path/to/oas2.yml',
  'path/to/oas3.yml',
]

Promise.allSettled(
  filesToMerge.map(async (file) => {
    // Load YAML
    const oas = await loadOas(file);

    return {
      oas,
    };

  }),
).then((mergeInputs) => {
  // Combine all docs together
  const merged = merge(mergeInputs);
  // Write merged outputs to output file
  const outputPath = 'path/to/output.yml';
  // Note: The JSON stringify and parse is required to strip the undefined values: https://github.com/nodeca/js-yaml/issues/571
  const fileContents = yaml.dump(JSON.parse(JSON.stringify(merged.output)), { indent: 2 });

  fs.writeFileSync(outputPath, fileContents);
});
```
Most of it is taken from the `openapi-merge-cli` package in this repo.
Things to note:
- I'm only using YAML files, so I'm not parsing any JSON files
- I have to use `Promise.all` as I'm using an async function to load the YAML

I'm sure there's lots of ways it can be improved, but that's a rough outline of how I've got it working so far.

**Comment by robertmassaioli** [comment]
Please check out the readme now, is this good or do you need more: https://www.npmjs.com/package/openapi-merge

**Comment by robertmassaioli** [comment]
I'm going to assume that these docs are sufficient and close this issue out. Please comment if they are not and good luck!
